# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'ubuntu-latest'
trigger:
- master
- dev

variables:
  MajorVersion: 1
  MinorVersion: 0
  InitialReleaseTagNumber: 1
  IncrementReleaseTagNumber: $[counter(variables['InitialReleaseTagNumber'], 0)]  
steps:

# - script: sudo gem install fastlane -NV
#   displayName: 'Install fastlane'

# - script: |
#     cd android
#     sudo chmod -R 777 $(Agent.BuildDirectory)
#     sudo fastlane beta
#   displayName: 'Build android'

- script: |
   sudo chmod -R 777 $(Agent.BuildDirectory)
   npm install
   cd android
   ./gradlew assembleRelease
  displayName: 'Build apk'


- task: CopyFiles@2
  inputs:
    contents: '**/*.apk'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1

- task: GitHubRelease@1
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    gitHubConnection: 'bryht'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: 'v$(MajorVersion).$(MinorVersion).$(IncrementReleaseTagNumber)'
    assets: |
         $(Build.ArtifactStagingDirectory)/*.apk
         $(Build.ArtifactStagingDirectory)/README.txt
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'